---
- name: Install tools
  hosts: localhost
  gather_facts: true
  roles:
    - {role: macOS_install, when: "ansible_facts['os_family'] == 'Darwin'"}
    - {role: Ubuntu_install, when: "ansible_facts['os_family'] == 'Debian'"}
  become: yes
